[package]
name = "Tuple"
version = "0.1.0"
authors = ["Cy-zhen <18588982404@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
